name: Build .NET artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #build artifact to be used on azure app service
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          8.0.x
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DemoBlazorWebApp/DemoBlazorWebApp.csproj -c Release -o release --nologo
    - name: Upload dotnet artifact
      uses: actions/upload-artifact@v4
      with:
        name: Application_Artifact
        path: /home/runner/work/DemoBlazorWebApp/DemoBlazorWebApp/release/
    #build a docker image and push it to a docker registry to be used in a VM
    - name: Build the Docker image
      working-directory: DemoBlazorWebApp/
      run: docker build . -t viorel89/demoblazorewebapp:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push viorel89/demoblazorwebapp

