# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          8.0.x
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        project: DemoBlazorWebApp/DemoBlazorWebApp.csproj
        build-breaking: false
        security: 5.0-all
        performance: 5.0-all
        all-categories: 5.0-recommended
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DemoBlazorWebApp/DemoBlazorWebApp.csproj -c Release -o release --nologo
    - name: Upload dotnet artifact
      uses: actions/upload-artifact@v4
      with:
        name: Application_Artifact
        path: /home/runner/work/DemoBlazorWebApp/DemoBlazorWebApp/release/

